import icon from "../static/image/w9999gold-icon.png";
import React, { useEffect, useState } from "react";
import { Link, Navigate } from "react-router-dom";
import { CgProfile } from "react-icons/cg";
import { useApp } from "../Context";

import "../static/css/navbar.css";

const RegularNavBar = () => {
  const context = useApp();
  const member = context.member;
  const [isChecked, setIsChecked] = useState(false);

  const toggleCheck = () => {
    setIsChecked(!isChecked);
  };

  // this is generated by ChatGPT
  useEffect(() => {
    const handleResize = () => {
      if (window.innerWidth > 576 && isChecked) {
        setIsChecked(false);
      }
    };
    window.addEventListener("resize", handleResize);
    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, [isChecked]);

  if (!member.hasBackstagePrivilege) {
    return <Navigate replace={true} to={"/"}></Navigate>;
  } else {
    return (
      <nav
        id="navbar"
        className="width-100 d-flex flex-ai-center flex-jc-center"
        style={{ background: "#696969" }}
      >
        <div className="d-flex flex-ai-center flex-jc-between pr-5 pl-5">
          <Link
            to="/backstage"
            className="d-flex flex-ai-center flex-jc-center"
          >
            <img src={icon} alt="icon" width="50" height="24.33"></img>
            <span style={{ color: "#FFFFFF" }}>後台管理</span>
          </Link>

          <div>
            <label
              className="font-size-20"
              id="navbar-toggler-label"
              style={{ color: "#FFFFFF" }}
              htmlFor="navbar-toggler"
            >
              &#9776;
            </label>

            <input
              type="checkbox"
              id="navbar-toggler"
              checked={isChecked}
              onChange={toggleCheck}
            ></input>

            <div id="navbar-foldable">
              <div onClick={toggleCheck}></div>
              <ul>
                <li onClick={() => setIsChecked(false)}>
                  <Link style={{ color: "#FFFFFF" }} to="cover">
                    首頁管理
                  </Link>
                </li>

                <li onClick={toggleCheck}>
                  <Link style={{ color: "#FFFFFF" }} to="gold-price-report">
                    金價管理
                  </Link>
                </li>

                <li onClick={() => setIsChecked(false)}>
                  <Link style={{ color: "#FFFFFF" }} to="products">
                    產品管理
                  </Link>
                </li>

                <li onClick={() => setIsChecked(false)}>
                  <Link style={{ color: "#FFFFFF" }} to="cart">
                    訂單管理
                  </Link>
                </li>

                <li>
                  <Link style={{ color: "#fff" }} to="/member">
                    <CgProfile />
                    {member.name}
                  </Link>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </nav>
    );
  }
};

export default RegularNavBar;
