import icon from "../static/image/w9999gold-icon.png";
import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
// navbar
import '../static/css/navbar.css'

const StudioNavBar = () => {
  
  const [isChecked, setIsChecked] = useState(false);

  const toggleCheck = () => {
    setIsChecked(!isChecked);
  };

  // this is generated by ChatGPT
  useEffect(() => {
    const handleResize = () => {
      if (window.innerWidth > 576 && isChecked) {
        setIsChecked(false);
      }
    };
    window.addEventListener('resize', handleResize);
    return () => {
      window.removeEventListener('resize', handleResize);
    };
  }, [isChecked]);

  return (
    <nav id="navbar"
      className="width-100 d-flex flex-ai-center flex-jc-center"
      style={{
        height: "100px",
        background: "linear-gradient(90deg, #A76E00 0.77%, #FF9C28 33.85%, #FFB750 66.92%, #DAAA00 100%)",
      }}
    >
      <div style={{color: "black"}}
        className="d-flex flex-ai-center flex-jc-between pr-5 pl-5" 
      >

        <a href="/" className="d-flex">
          <img src={icon} alt="icon" width="50" height="24.33"></img>
          <span style={{color: "#FFFFFF"}}>仕彩金飾</span>
        </a>

        <div>
          <label
            className="font-size-20"
            id="navbar-toggler-label"
            style={{ color: "#FFFFFF" }}
            htmlFor="navbar-toggler"
          >
            &#9776;
          </label>

          <input
            type="checkbox"
            id="navbar-toggler"
            checked={isChecked}
            onChange={toggleCheck}
          ></input>

          <div id="navbar-foldable">
            <div onClick={toggleCheck}></div>
            <ul>
              <li onClick={() => setIsChecked(false)}>
                <Link style={{ color: "#FFFFFF" }} to="/">
                  首頁
                </Link>
              </li>
              <li onClick={toggleCheck}>
                <Link style={{color: "#FFFFFF"}} to="/gold">黃金市價</Link>
              </li>
              <li onClick={() => setIsChecked(false)}>
                <Link style={{ color: "#FFFFFF" }} to="/product">
                  選擇產品
                </Link>
              </li>
            </ul>
          </div>
        </div>

      </div>
    </nav>
  );
};

export default StudioNavBar;